export type InsuranceCategory = 'life' | 'motor' | 'pension';

export interface GhanaInsurer {
  id: string;
  name: string;
  shortName: string;
  category: InsuranceCategory;
  keywords: string[];
  website: string;
  logoUrl?: string;
  brandColor: string;
}

// Ghana Life Insurance Companies (NIC Licensed) - Updated from NIC Portal January 2025
// Sorted alphabetically by name
export const lifeInsurers: GhanaInsurer[] = [
  {
    id: 'aster-life',
    name: 'Aster Life Ghana Limited',
    shortName: 'Aster Life',
    category: 'life',
    keywords: ['aster life', 'gn life'],
    website: 'https://www.gnlifeassurance.com',
    brandColor: '#27AE60',
  },
  {
    id: 'beige-assure',
    name: 'Beige Assure Company',
    shortName: 'Beige Assure',
    category: 'life',
    keywords: ['beige assure', 'beige'],
    website: 'https://www.beigeassure.com',
    brandColor: '#C4A35A',
  },
  {
    id: 'enterprise-life',
    name: 'Enterprise Life Assurance Ltd',
    shortName: 'Enterprise Life',
    category: 'life',
    keywords: ['enterprise life', 'ela', 'enterprise assurance'],
    website: 'https://www.enterprisegroup.com.gh',
    brandColor: '#006633',
  },
  {
    id: 'first-insurance',
    name: 'First Insurance Company Limited',
    shortName: 'First Insurance',
    category: 'life',
    keywords: ['first insurance', 'first life'],
    website: 'https://www.firstinsurance.net',
    brandColor: '#1565C0',
  },
  {
    id: 'glico-life',
    name: 'GLICO Life Insurance Ltd',
    shortName: 'GLICO Life',
    category: 'life',
    keywords: ['glico life', 'glico'],
    website: 'https://www.glicolife.com',
    brandColor: '#1E3A5F',
  },
  {
    id: 'hollard-life',
    name: 'Hollard Life Assurance Ghana Ltd',
    shortName: 'Hollard Life',
    category: 'life',
    keywords: ['hollard life'],
    website: 'https://www.hollard.com.gh',
    brandColor: '#E31837',
  },
  {
    id: 'impact-life',
    name: 'Impact Life Insurance Limited Company',
    shortName: 'Impact Life',
    category: 'life',
    keywords: ['impact life', 'impact insurance'],
    website: 'https://www.impactlife.com.gh',
    brandColor: '#D35400',
  },
  {
    id: 'metropolitan-life',
    name: 'Metropolitan Life Insurance Ghana Ltd',
    shortName: 'Metropolitan Life',
    category: 'life',
    keywords: ['metropolitan', 'metlife ghana'],
    website: 'https://www.metropolitan.com.gh',
    brandColor: '#003399',
  },
  {
    id: 'milife',
    name: 'MiLife Company Limited',
    shortName: 'MiLife',
    category: 'life',
    keywords: ['milife', 'mi life'],
    website: 'https://www.milifeghana.com',
    brandColor: '#FF6B35',
  },
  {
    id: 'old-mutual-life',
    name: 'Old Mutual Life Assurance Company (Ghana) Limited',
    shortName: 'Old Mutual Life',
    category: 'life',
    keywords: ['old mutual', 'old mutual life'],
    website: 'https://www.oldmutual.com.gh',
    brandColor: '#00594C',
  },
  {
    id: 'pinnacle-life',
    name: 'Pinnacle Life Insurance Company Limited',
    shortName: 'Pinnacle Life',
    category: 'life',
    keywords: ['pinnacle life', 'donewell life'],
    website: 'https://www.pinnaclelife.com.gh',
    brandColor: '#1B4F72',
  },
  {
    id: 'prudential-life',
    name: 'Prudential Life Insurance Ghana',
    shortName: 'Prudential Life',
    category: 'life',
    keywords: ['prudential', 'prudential life'],
    website: 'https://www.prudential.com.gh',
    brandColor: '#ED1C24',
  },
  {
    id: 'quality-life',
    name: 'Quality Life Assurance Company Limited',
    shortName: 'Quality Life',
    category: 'life',
    keywords: ['quality life', 'qlac'],
    website: 'https://www.qlacgh.com',
    brandColor: '#8E44AD',
  },
  {
    id: 'sanlam-allianz-life',
    name: 'Sanlam Allianz Life Insurance Ghana Ltd',
    shortName: 'Sanlam Allianz Life',
    category: 'life',
    keywords: ['sanlam allianz life', 'sanlam life'],
    website: 'https://www.gh.sanlam.com',
    brandColor: '#00A651',
  },
  {
    id: 'sic-life',
    name: 'SIC Life Company Ltd',
    shortName: 'SIC Life',
    category: 'life',
    keywords: ['sic life', 'state insurance life'],
    website: 'https://www.siclife-gh.com',
    brandColor: '#004A8F',
  },
  {
    id: 'starlife',
    name: 'StarLife Assurance Company Limited',
    shortName: 'StarLife',
    category: 'life',
    keywords: ['starlife', 'star life'],
    website: 'https://www.starlife.com.gh',
    brandColor: '#FFD700',
  },
  {
    id: 'vanguard-life',
    name: 'Vanguard Life Assurance Company Limited',
    shortName: 'Vanguard Life',
    category: 'life',
    keywords: ['vanguard life', 'vanguard'],
    website: 'https://www.vanguardlife.com',
    brandColor: '#2E86AB',
  },
];

// Ghana Non-Life/Motor Insurance Companies (NIC Licensed) - Updated from NIC Portal January 2025
// Sorted alphabetically by name
export const motorInsurers: GhanaInsurer[] = [
  {
    id: 'activa-insurance',
    name: 'Activa International Insurance Company-Ghana Limited',
    shortName: 'Activa Insurance',
    category: 'motor',
    keywords: ['activa insurance', 'activa'],
    website: 'https://www.activa-ghana.com',
    brandColor: '#27AE60',
  },
  {
    id: 'bedrock-insurance',
    name: 'Bedrock Insurance Company Limited',
    shortName: 'Bedrock Insurance',
    category: 'motor',
    keywords: ['bedrock insurance', 'bedrock'],
    website: 'https://www.bedrockinsurancegh.com',
    brandColor: '#795548',
  },
  {
    id: 'best-assurance',
    name: 'Best Assurance Company Limited',
    shortName: 'Best Assurance',
    category: 'motor',
    keywords: ['best assurance', 'best insurance'],
    website: 'https://www.bestassurance.com.gh',
    brandColor: '#D35400',
  },
  {
    id: 'coronation-insurance',
    name: 'Coronation Insurance Ghana Ltd',
    shortName: 'Coronation Insurance',
    category: 'motor',
    keywords: ['coronation', 'wapic'],
    website: 'https://www.wapic.com/gh',
    brandColor: '#6A1B9A',
  },
  {
    id: 'donewell-insurance',
    name: 'Donewell Insurance Ltd',
    shortName: 'Donewell Insurance',
    category: 'motor',
    keywords: ['donewell insurance', 'donewell'],
    website: 'https://www.donewellinsurance.com',
    brandColor: '#1B4F72',
  },
  {
    id: 'enterprise-insurance',
    name: 'Enterprise Insurance Ltd',
    shortName: 'Enterprise Insurance',
    category: 'motor',
    keywords: ['enterprise insurance', 'eic'],
    website: 'https://www.enterprisegroup.com.gh',
    brandColor: '#006633',
  },
  {
    id: 'ghana-union',
    name: 'Ghana Union Assurance Ltd',
    shortName: 'Ghana Union',
    category: 'motor',
    keywords: ['ghana union', 'gua'],
    website: 'https://www.ghanaunionassurancecompany.com',
    brandColor: '#00695C',
  },
  {
    id: 'glico-general',
    name: 'Glico General Insurance Ltd',
    shortName: 'Glico General',
    category: 'motor',
    keywords: ['glico general', 'glico insurance'],
    website: 'https://www.glicogeneral.com',
    brandColor: '#1E3A5F',
  },
  {
    id: 'hollard-insurance',
    name: 'Hollard Insurance Ghana Ltd',
    shortName: 'Hollard Insurance',
    category: 'motor',
    keywords: ['hollard', 'hollard insurance'],
    website: 'https://www.hollard.com.gh',
    brandColor: '#E31837',
  },
  {
    id: 'imperial-general',
    name: 'Imperial General Assurance Company Limited',
    shortName: 'Imperial General',
    category: 'motor',
    keywords: ['imperial general', 'imperial'],
    website: 'https://www.imperialgeneral.com',
    brandColor: '#1976D2',
  },
  {
    id: 'loyalty-insurance',
    name: 'Loyalty Insurance Company Limited',
    shortName: 'Loyalty Insurance',
    category: 'motor',
    keywords: ['loyalty insurance', 'loyalty'],
    website: 'https://www.loyaltyinsurancegh.com',
    brandColor: '#2980B9',
  },
  {
    id: 'millennium-insurance',
    name: 'Millennium Insurance Company Limited',
    shortName: 'Millennium Insurance',
    category: 'motor',
    keywords: ['millennium insurance', 'millennium'],
    website: 'https://www.millenniuminsurance.com.gh',
    brandColor: '#16A085',
  },
  {
    id: 'nsia-insurance',
    name: 'NSIA Insurance Company Limited',
    shortName: 'NSIA Insurance',
    category: 'motor',
    keywords: ['nsia insurance', 'nsia'],
    website: 'https://www.nsiainsurance.com.gh',
    brandColor: '#E65100',
  },
  {
    id: 'phoenix-insurance',
    name: 'Phoenix Insurance Company Limited',
    shortName: 'Phoenix Insurance',
    category: 'motor',
    keywords: ['phoenix insurance', 'phoenix'],
    website: 'https://www.phoenixghana.com',
    brandColor: '#FF6600',
  },
  {
    id: 'prime-insurance',
    name: 'Prime Insurance Company Limited',
    shortName: 'Prime Insurance',
    category: 'motor',
    keywords: ['prime insurance', 'prime'],
    website: 'https://www.primeinsuranceghana.com',
    brandColor: '#4A148C',
  },
  {
    id: 'priority-insurance',
    name: 'Priority Insurance Ltd',
    shortName: 'Priority Insurance',
    category: 'motor',
    keywords: ['priority insurance', 'priority'],
    website: 'https://www.priorityinsurance.com.gh',
    brandColor: '#C0392B',
  },
  {
    id: 'provident-insurance',
    name: 'Provident Insurance Company Limited',
    shortName: 'Provident Insurance',
    category: 'motor',
    keywords: ['provident insurance', 'provident'],
    website: 'https://www.provident-gh.com',
    brandColor: '#00838F',
  },
  {
    id: 'quality-insurance',
    name: 'Quality Insurance Company Limited',
    shortName: 'Quality Insurance',
    category: 'motor',
    keywords: ['quality insurance', 'qic'],
    website: 'https://www.qicghana.com',
    brandColor: '#C62828',
  },
  {
    id: 'regency-nem',
    name: 'Regency Nem Insurance Ghana Limited',
    shortName: 'Regency NEM',
    category: 'motor',
    keywords: ['regency nem', 'regency insurance'],
    website: 'https://www.regencynem.com',
    brandColor: '#8B0000',
  },
  {
    id: 'sanlam-allianz-general',
    name: 'Sanlam Allianz General Insurance Ghana Ltd',
    shortName: 'Sanlam Allianz General',
    category: 'motor',
    keywords: ['sanlam allianz', 'sanlam general'],
    website: 'https://www.gh.sanlam.com',
    brandColor: '#003781',
  },
  {
    id: 'serene-insurance',
    name: 'Serene Insurance Company',
    shortName: 'Serene Insurance',
    category: 'motor',
    keywords: ['serene insurance'],
    website: 'https://www.sereneinsurance.com',
    brandColor: '#9B59B6',
  },
  {
    id: 'sic-insurance',
    name: 'SIC Insurance PLC',
    shortName: 'SIC Insurance',
    category: 'motor',
    keywords: ['sic insurance', 'state insurance'],
    website: 'https://www.sic-gh.com',
    brandColor: '#004A8F',
  },
  {
    id: 'star-assurance',
    name: 'Star Assurance Limited Company',
    shortName: 'Star Assurance',
    category: 'motor',
    keywords: ['star assurance', 'star insurance'],
    website: 'https://www.starassurance.com',
    brandColor: '#FFD700',
  },
  {
    id: 'sunu-assurances',
    name: 'SUNU Assurances Ghana Ltd',
    shortName: 'SUNU Assurances',
    category: 'motor',
    keywords: ['sunu', 'sunu assurances'],
    website: 'https://www.sunu-group.com',
    brandColor: '#FF5722',
  },
  {
    id: 'unique-insurance',
    name: 'Unique Insurance Company Limited',
    shortName: 'Unique Insurance',
    category: 'motor',
    keywords: ['unique insurance', 'uic'],
    website: 'https://www.uicghana.org',
    brandColor: '#16A085',
  },
  {
    id: 'vanguard-assurance',
    name: 'Vanguard Assurance Company Limited',
    shortName: 'Vanguard Assurance',
    category: 'motor',
    keywords: ['vanguard assurance', 'vanguard'],
    website: 'https://www.vanguardassurance.com',
    brandColor: '#2E86AB',
  },
];

// Ghana Pension & Trustees (NPRA Licensed) - Updated January 2025
// Sorted alphabetically by name
export const pensionProviders: GhanaInsurer[] = [
  {
    id: 'axis-pensions',
    name: 'Axis Pension Trust',
    shortName: 'Axis Pensions',
    category: 'pension',
    keywords: ['axis pension', 'axis trust'],
    website: 'https://www.axispensiontrust.com',
    brandColor: '#C62828',
  },
  {
    id: 'dalex-pensions',
    name: 'Dalex Finance & Pensions',
    shortName: 'Dalex Pensions',
    category: 'pension',
    keywords: ['dalex pensions', 'dalex finance'],
    website: 'https://www.dalexfinance.com',
    brandColor: '#E65100',
  },
  {
    id: 'ecobank-pensions',
    name: 'Ecobank Pension Custody Ghana',
    shortName: 'Ecobank Pensions',
    category: 'pension',
    keywords: ['ecobank pensions', 'ecobank pension'],
    website: 'https://www.ecobank.com',
    brandColor: '#003399',
  },
  {
    id: 'enterprise-trustees',
    name: 'Enterprise Trustees Limited',
    shortName: 'Enterprise Trustees',
    category: 'pension',
    keywords: ['enterprise trustees', 'etl', 'enterprise pension'],
    website: 'https://www.enterprisetrustees.com.gh',
    brandColor: '#006633',
  },
  {
    id: 'first-pension',
    name: 'First Pension Trust Ghana',
    shortName: 'First Pension',
    category: 'pension',
    keywords: ['first pension', 'first pension trust'],
    website: 'https://www.firstpensiontrust.com',
    brandColor: '#4A148C',
  },
  {
    id: 'glico-pensions',
    name: 'GLICO Pensions Trustee Company',
    shortName: 'GLICO Pensions',
    category: 'pension',
    keywords: ['glico pensions', 'glico pension'],
    website: 'https://www.glicopensions.com',
    brandColor: '#1E3A5F',
  },
  {
    id: 'metropolitan-pensions',
    name: 'Metropolitan Pensions Trust',
    shortName: 'Metropolitan Pensions',
    category: 'pension',
    keywords: ['metropolitan pensions'],
    website: 'https://www.metropolitan.com.gh',
    brandColor: '#00A651',
  },
  {
    id: 'npra',
    name: 'National Pensions Regulatory Authority',
    shortName: 'NPRA',
    category: 'pension',
    keywords: ['npra', 'national pensions', 'pensions regulator'],
    website: 'https://www.npra.gov.gh',
    brandColor: '#1976D2',
  },
  {
    id: 'negotiated-benefits',
    name: 'Negotiated Benefits Trust Ghana',
    shortName: 'NBT Ghana',
    category: 'pension',
    keywords: ['negotiated benefits', 'nbt'],
    website: 'https://www.nbt.com.gh',
    brandColor: '#00695C',
  },
  {
    id: 'old-mutual-pensions',
    name: 'Old Mutual Pension Trust Ghana',
    shortName: 'Old Mutual Pensions',
    category: 'pension',
    keywords: ['old mutual pensions', 'old mutual pension'],
    website: 'https://www.oldmutual.com.gh',
    brandColor: '#00594C',
  },
  {
    id: 'pensions-alliance',
    name: 'Pensions Alliance Trust Ghana',
    shortName: 'PAT Ghana',
    category: 'pension',
    keywords: ['pensions alliance', 'pat', 'alliance trust'],
    website: 'https://www.pensionsalliance.com.gh',
    brandColor: '#2E7D32',
  },
  {
    id: 'petra-trust',
    name: 'Petra Trust Company Limited',
    shortName: 'Petra Trust',
    category: 'pension',
    keywords: ['petra trust', 'petra'],
    website: 'https://www.petratrust.com',
    brandColor: '#6A1B9A',
  },
  {
    id: 'ssnit',
    name: 'Social Security & National Insurance Trust',
    shortName: 'SSNIT',
    category: 'pension',
    keywords: ['ssnit', 'social security'],
    website: 'https://www.ssnit.org.gh',
    brandColor: '#0277BD',
  },
  {
    id: 'stanbic-pensions',
    name: 'Stanbic Pension Managers Ghana',
    shortName: 'Stanbic Pensions',
    category: 'pension',
    keywords: ['stanbic pensions', 'stanbic pension'],
    website: 'https://www.stanbicbank.com.gh',
    brandColor: '#0033A0',
  },
  {
    id: 'united-pensions',
    name: 'United Pensions Trustees Ghana',
    shortName: 'United Pensions',
    category: 'pension',
    keywords: ['united pensions', 'unitrust'],
    website: 'https://www.unitedpensions.com.gh',
    brandColor: '#1565C0',
  },
];

export const allInsurers = [...lifeInsurers, ...motorInsurers, ...pensionProviders];

export const categoryConfig: Record<InsuranceCategory, { label: string; icon: string; color: string }> = {
  life: { label: 'Life Insurance', icon: '💚', color: 'from-emerald-600 to-green-600' },
  motor: { label: 'Motor Insurance', icon: '🚗', color: 'from-blue-600 to-indigo-600' },
  pension: { label: 'Pension & Trustees', icon: '🏦', color: 'from-purple-600 to-violet-600' },
};
