
ALTER TABLE public.insurer_metrics
  ADD COLUMN IF NOT EXISTS annuities numeric,
  ADD COLUMN IF NOT EXISTS microinsurance numeric,
  ADD COLUMN IF NOT EXISTS unit_linked numeric,
  ADD COLUMN IF NOT EXISTS investment_linked numeric,
  ADD COLUMN IF NOT EXISTS critical_illness numeric,
  ADD COLUMN IF NOT EXISTS other_products numeric,
  ADD COLUMN IF NOT EXISTS insurance_service_result numeric,
  ADD COLUMN IF NOT EXISTS insurance_service_expenses numeric,
  ADD COLUMN IF NOT EXISTS total_attributable_expenses numeric,
  ADD COLUMN IF NOT EXISTS non_attributable_expenses numeric,
  ADD COLUMN IF NOT EXISTS acquisition_cashflow numeric,
  ADD COLUMN IF NOT EXISTS insurance_finance_income numeric,
  ADD COLUMN IF NOT EXISTS other_income numeric,
  ADD COLUMN IF NOT EXISTS total_investments numeric,
  ADD COLUMN IF NOT EXISTS total_liabilities numeric,
  ADD COLUMN IF NOT EXISTS total_receivables numeric,
  ADD COLUMN IF NOT EXISTS ppe numeric,
  ADD COLUMN IF NOT EXISTS cash_balance numeric,
  ADD COLUMN IF NOT EXISTS insurance_contract_assets numeric,
  ADD COLUMN IF NOT EXISTS reinsurance_contract_assets numeric,
  ADD COLUMN IF NOT EXISTS insurance_contract_liabilities numeric,
  ADD COLUMN IF NOT EXISTS reinsurance_contract_liabilities numeric,
  ADD COLUMN IF NOT EXISTS technical_results_margin numeric,
  ADD COLUMN IF NOT EXISTS attributable_expense_ratio numeric,
  ADD COLUMN IF NOT EXISTS non_attributable_expense_ratio numeric,
  ADD COLUMN IF NOT EXISTS share_insurance_service_results numeric;
